spring:
  application:
    security:
      jwt:
        secret-key: fabd4036fe9c776fcc09c8d0b1cfbd508ef660f6674c32236de73443f9387981
        expiration: 86400000
  datasource:
    url: jdbc:postgresql://localhost:5434/taskflow
    username: alina
    password: tomchak
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  data:
    redis:
      host: localhost
      port: 6379